# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'afficherEmploye.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from employer import Employe
from PyQt5.QtWidgets import QDialog ,QApplication

class Ui_Afficher_employe(object):
    def setupUi(self, Afficher_employe):
        Afficher_employe.setObjectName("Afficher_employe")
        Afficher_employe.resize(1285, 571)
        Afficher_employe.setStyleSheet("background-color: #bbff00; \n"
"")
        self.tableWidget = QtWidgets.QTableWidget(Afficher_employe)
        self.tableWidget.setGeometry(QtCore.QRect(110, 50, 1011, 461))
        self.tableWidget.setMaximumSize(QtCore.QSize(1011, 461))
        self.tableWidget.setStyleSheet("background-color: #ffffff; /* Fully opaque */\n"
"border: 2px solid black;\n"
"  border-radius: 5px;")
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustIgnored)
        self.tableWidget.setAutoScrollMargin(15)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)

        self.retranslateUi(Afficher_employe)
        QtCore.QMetaObject.connectSlotsByName(Afficher_employe)
        
        self.afficherData()

    def retranslateUi(self, Afficher_employe):
        _translate = QtCore.QCoreApplication.translate
        Afficher_employe.setWindowTitle(_translate("Afficher_employe", "Dialog"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Afficher_employe", "#"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Afficher_employe", "NOM"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Afficher_employe", "Prenom"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Afficher_employe", "Email"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Afficher_employe", "Phone"))
    
    
    def afficherData(self) :
        employes=Employe.selectall()
        print(employes)
        row=0
        self.tableWidget.setRowCount(len(employes))
        for employe in employes:
            self.tableWidget.setItem(row,0,QtWidgets.QTableWidgetItem(f'{employe[0]}'))
            self.tableWidget.setItem(row,1,QtWidgets.QTableWidgetItem(employe[1]))
            self.tableWidget.setItem(row,2,QtWidgets.QTableWidgetItem(employe[2]))
            self.tableWidget.setItem(row,3,QtWidgets.QTableWidgetItem(employe[3]))
            self.tableWidget.setItem(row,4,QtWidgets.QTableWidgetItem(employe[4]))
            
            row=row+1
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Afficher_employe = QtWidgets.QDialog()
    ui = Ui_Afficher_employe()
    ui.setupUi(Afficher_employe)
    Afficher_employe.show()
    sys.exit(app.exec_())
