sonar.projectKey=FaceS
sonar.projectName=FaceSmart
sonar.sources=src,ui
sonar.host.url=http://localhost:9000
sonar.exclusions=**/.venv/**,**/.git/**,**/__pycache__/**,**/*.pyc,docs/**,images/**,resources/**,learn/**,face_recognition.py
sonar.token=sqp_eef9f9ed3d46fb8a399cfd87a1e4dfd0b9601696
sonar.python.version=3.10
sonar.sourceEncoding=UTF-8
sonar.profile=FaceSmart Python Profile