# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tache_supprimer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from tache import Tache
from PyQt5.QtWidgets import *

class Ui_Dialog_supprimer(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(807, 489)
        Dialog.setStyleSheet("background-color:#CDBEFF;")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(230, 30, 411, 431))
        self.label_2.setStyleSheet("border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius: 30px;\n"
"background-color:#332562;\n"
"\n"
"")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(390, 50, 111, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:90px;\n"
"")
        self.label_5.setObjectName("label_5")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(240, 220, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:20px;\n"
"border:none;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.comboBox = QtWidgets.QComboBox(Dialog)
        self.comboBox.setGeometry(QtCore.QRect(270, 260, 341, 31))
        self.comboBox.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:20px;\n"
"border:none;\n"
"border-bottom: 2px solid #FFFFFF;")
        self.comboBox.setObjectName("comboBox")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(340, 370, 171, 51))
        self.pushButton.setStyleSheet("\n"
"font-size:20px;\n"
"border:none;\n"
"border: 2px solid #FFFFFF;\n"
"border-radius: 10px;")
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.pushButton.clicked.connect(self.supprimer_tache)
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_5.setText(_translate("Dialog", ""))
        self.pushButton_4.setText(_translate("Dialog", "Tache :"))
        self.pushButton.setText(_translate("Dialog", "Supprimer"))
        self.afficher_Tache()

    def afficher_Tache(self):
        taches=Tache.read()
        for tache in taches:
          self.comboBox.addItem(tache[1]) 
        
    def supprimer_tache(self):
        libelle=self.comboBox.currentText()
        result=Tache.supprimer(libelle)
        if(result=='Done'):
           msg = QMessageBox()
           msg.setWindowTitle("Emsi_Smart ")
           msg.setText("la tache a été Supprimer correctement :)")
           msg.setIcon(QMessageBox.Warning)
           x = msg.exec_()
        else:
            msg = QMessageBox()
            msg.setWindowTitle("Emsi_Smart ")
            msg.setText("La suppretion a échoué :)")
            msg.setIcon(QMessageBox.Critical)
            x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_supprimer()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
