# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chercher.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from chercher_emp import Ui_Dialog_emp 
from chaercher_period import Ui_Dialog_periode
from chercher_tache2 import Ui_Dialog_res_tache

class Ui_Dialog_chercher(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1281, 538)
        Dialog.setStyleSheet("background-color:#CDBEFF;")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(60, 90, 351, 351))
        self.label.setStyleSheet("border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius: 30px;\n"
"background-color:#332562;\n"
"\n"
"")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(160, 120, 191, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:140px")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(480, 210, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(460, 90, 351, 351))
        self.label_4.setStyleSheet("\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius: 30px;\n"
"background-color:#332562;\n"
"")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(880, 90, 351, 351))
        self.label_5.setStyleSheet("\n"
"border: 2px solid rgba(0, 0, 0, 255);\n"
"border-radius: 30px;\n"
"background-color:#332562;\n"
"")
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(90, 300, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:25px;\n"
"border:none;")
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(Dialog)
        self.label_6.setGeometry(QtCore.QRect(560, 120, 191, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:140px")
        self.label_6.setObjectName("label_6")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(490, 300, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:25px;\n"
"border:none;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QtWidgets.QLabel(Dialog)
        self.label_7.setGeometry(QtCore.QRect(980, 120, 191, 151))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:140px")
        self.label_7.setObjectName("label_7")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(910, 300, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:25px;\n"
"border:none;")
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        
    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_2.setText(_translate("Dialog", ""))
        self.label_3.setText(_translate("Dialog", "TextLabel"))
        self.pushButton.setText(_translate("Dialog", " Chercher Un Employé "))
        self.label_6.setText(_translate("Dialog", ""))
        self.pushButton_2.setText(_translate("Dialog", " Chercher Une tache"))
        self.label_7.setText(_translate("Dialog", ""))
        self.pushButton_3.setText(_translate("Dialog", " Chercher une Periode"))

        self.pushButton.clicked.connect(self.open_chercher_emp)
        self.pushButton_2.clicked.connect(self.open_chercher_tache)
        self.pushButton_3.clicked.connect(self.open_chercher_periode)
    
    def open_chercher_emp(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog_emp()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()
        

    def open_chercher_periode(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog_periode()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()
        
    def open_chercher_tache(self):
        self.Dialog = QtWidgets.QDialog()
        self.ui = Ui_Dialog_res_tache()
        self.ui.setupUi(self.Dialog)
        self.Dialog.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog_chercher()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
