# Form implementation generated from reading ui file 'c:\Users\Hp\Desktop\projet-pfa-2\sidebar_test.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1258, 576)
        MainWindow.setStyleSheet("background-color: rgb(130, 96, 255);")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_2.setStyleSheet("QWidget{\n"
"background-color:#332562;\n"
"color:white;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:white;\n"
"text-align:left;\n"
"height:30px;\n"
"border : none;\n"
"padding-left:10px;\n"
"border-top-left-radius:10px;\n"
"border-bottom-left-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:#CDBEFF;\n"
"color:#332562;\n"
"font-weight:bold;\n"
"}\n"
"")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_4.setContentsMargins(-1, -1, 0, -1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, 20, -1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget_2)
        self.label_2.setMinimumSize(QtCore.QSize(40, 40))
        self.label_2.setMaximumSize(QtCore.QSize(40, 40))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/resources/profile_pic.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout_2.setSpacing(15)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.dashboard2 = QtWidgets.QPushButton(parent=self.widget_2)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/resources/dashboard_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon.addPixmap(QtGui.QPixmap(":/resources/dashboard.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.dashboard2.setIcon(icon)
        self.dashboard2.setCheckable(True)
        self.dashboard2.setChecked(True)
        self.dashboard2.setAutoExclusive(True)
        self.dashboard2.setObjectName("dashboard2")
        self.verticalLayout_2.addWidget(self.dashboard2)
        self.create2 = QtWidgets.QPushButton(parent=self.widget_2)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/resources/tabs.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon1.addPixmap(QtGui.QPixmap(":/resources/tabsbb.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.create2.setIcon(icon1)
        self.create2.setCheckable(True)
        self.create2.setAutoExclusive(True)
        self.create2.setObjectName("create2")
        self.verticalLayout_2.addWidget(self.create2)
        self.update2 = QtWidgets.QPushButton(parent=self.widget_2)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/resources/user-avatar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon2.addPixmap(QtGui.QPixmap(":/resources/user-avatarbb.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.update2.setIcon(icon2)
        self.update2.setCheckable(True)
        self.update2.setAutoExclusive(True)
        self.update2.setObjectName("update2")
        self.verticalLayout_2.addWidget(self.update2)
        self.pushButton_8 = QtWidgets.QPushButton(parent=self.widget_2)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/resources/delete.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        icon3.addPixmap(QtGui.QPixmap("c:\\Users\\Hp\\Desktop\\projet-pfa-2\\resources/delete11.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.On)
        self.pushButton_8.setIcon(icon3)
        self.pushButton_8.setCheckable(True)
        self.pushButton_8.setAutoExclusive(True)
        self.pushButton_8.setObjectName("pushButton_8")
        self.verticalLayout_2.addWidget(self.pushButton_8)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        spacerItem = QtWidgets.QSpacerItem(20, 231, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.pushButton_10 = QtWidgets.QPushButton(parent=self.widget_2)
        self.pushButton_10.setStyleSheet("QPushButton{\n"
"text-align: left;\n"
"}")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/resources/log_out_white.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setCheckable(True)
        self.pushButton_10.setObjectName("pushButton_10")
        self.verticalLayout_4.addWidget(self.pushButton_10)
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setStyleSheet("QWidget{\n"
"background-color: #332562;\n"
"}\n"
"\n"
"QPushButton{\n"
"color:white;\n"
"height:30px;\n"
"border : none;\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"background-color:#CDBEFF;\n"
"color:#1F95EF;\n"
"font-weight:bold;\n"
"}")
        self.widget.setObjectName("widget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_3.setContentsMargins(11, 11, 11, 11)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setMinimumSize(QtCore.QSize(40, 40))
        self.label.setMaximumSize(QtCore.QSize(40, 40))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/resources/profile_pic.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(-1, 6, -1, -1)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dashboard1 = QtWidgets.QPushButton(parent=self.widget)
        self.dashboard1.setText("")
        self.dashboard1.setIcon(icon)
        self.dashboard1.setCheckable(True)
        self.dashboard1.setChecked(True)
        self.dashboard1.setAutoExclusive(True)
        self.dashboard1.setObjectName("dashboard1")
        self.verticalLayout.addWidget(self.dashboard1)
        self.create1 = QtWidgets.QPushButton(parent=self.widget)
        self.create1.setText("")
        self.create1.setIcon(icon1)
        self.create1.setCheckable(True)
        self.create1.setAutoExclusive(True)
        self.create1.setObjectName("create1")
        self.verticalLayout.addWidget(self.create1)
        self.update1 = QtWidgets.QPushButton(parent=self.widget)
        self.update1.setText("")
        self.update1.setIcon(icon2)
        self.update1.setCheckable(True)
        self.update1.setAutoExclusive(True)
        self.update1.setObjectName("update1")
        self.verticalLayout.addWidget(self.update1)
        self.delete1 = QtWidgets.QPushButton(parent=self.widget)
        self.delete1.setText("")
        self.delete1.setIcon(icon3)
        self.delete1.setCheckable(True)
        self.delete1.setAutoExclusive(True)
        self.delete1.setObjectName("delete1")
        self.verticalLayout.addWidget(self.delete1)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 231, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.pushButton_9 = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton_9.setText("")
        self.pushButton_9.setIcon(icon4)
        self.pushButton_9.setCheckable(True)
        self.pushButton_9.setObjectName("pushButton_9")
        self.verticalLayout_3.addWidget(self.pushButton_9)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_3.setStyleSheet("background-color: rgb(51, 37, 98);")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_5.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.widget_4 = QtWidgets.QWidget(parent=self.widget_3)
        self.widget_4.setStyleSheet("QWidget{\n"
"background-color:#332562;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.pushButton_11 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_11.setStyleSheet("border:none;")
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/resources/menu.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_11.setCheckable(True)
        self.pushButton_11.setChecked(False)
        self.pushButton_11.setAutoExclusive(False)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_3.addWidget(self.pushButton_11)
        spacerItem2 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.label_4 = QtWidgets.QLabel(parent=self.widget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(143, 255, 224);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.pushButton_12 = QtWidgets.QPushButton(parent=self.widget_4)
        self.pushButton_12.setStyleSheet("border:none;")
        self.pushButton_12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/resources/image (1).png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_12.setIcon(icon6)
        self.pushButton_12.setIconSize(QtCore.QSize(22, 22))
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_3.addWidget(self.pushButton_12)
        self.verticalLayout_5.addWidget(self.widget_4)
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.widget_3)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(10)
        font.setBold(False)
        self.stackedWidget.setFont(font)
        self.stackedWidget.setStyleSheet("border-top-right-radius:6px;\n"
"border-bottom-right-radius:6px;\n"
"background-color: #CDBEFF;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.dash_p = QtWidgets.QWidget()
        self.dash_p.setStyleSheet("")
        self.dash_p.setObjectName("dash_p")
        self.label_11 = QtWidgets.QLabel(parent=self.dash_p)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 1121, 531))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap(":/resources/BG.jpg"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(parent=self.dash_p)
        self.label_12.setGeometry(QtCore.QRect(30, 10, 621, 151))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("\n"
"color: rgb(170, 0, 255);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(parent=self.dash_p)
        self.label_13.setGeometry(QtCore.QRect(50, 140, 571, 81))
        font = QtGui.QFont()
        font.setPointSize(40)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("\n"
"color: rgb(170, 0, 255);")
        self.label_13.setObjectName("label_13")
        self.label_17 = QtWidgets.QLabel(parent=self.dash_p)
        self.label_17.setGeometry(QtCore.QRect(20, 460, 641, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.dash_p)
        self.pushButton_4.setGeometry(QtCore.QRect(100, 320, 151, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("border: 2px solid #FFFFFF;\n"
"border-radius: 10px;\n"
"background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:40px")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.dash_p)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 320, 161, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(-1)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setStyleSheet("border: 2px solid #FFFFFF;\n"
"border-radius: 10px;\n"
"background-color:#332562;\n"
"color:#FFFFFF;\n"
"font-size:40px")
        self.pushButton_5.setObjectName("pushButton_5")
        self.stackedWidget.addWidget(self.dash_p)
        self.create_p = QtWidgets.QWidget()
        self.create_p.setStyleSheet("")
        self.create_p.setObjectName("create_p")
        self.widget_5 = QtWidgets.QWidget(parent=self.create_p)
        self.widget_5.setGeometry(QtCore.QRect(250, 60, 471, 391))
        self.widget_5.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(170, 170, 255);\n"
"")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(parent=self.widget_5)
        self.label_5.setMinimumSize(QtCore.QSize(50, 50))
        self.label_5.setMaximumSize(QtCore.QSize(50, 50))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap(":/resources/tabsbb.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_5.addWidget(self.lineEdit)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_2.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_6.addWidget(self.lineEdit_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("padding-right:2px;")
        self.label_8.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.label_8.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.label_8.setMidLineWidth(0)
        self.label_8.setTextFormat(QtCore.Qt.TextFormat.AutoText)
        self.label_8.setScaledContents(False)
        self.label_8.setIndent(-1)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.lineEdit_3 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_3.setMinimumSize(QtCore.QSize(30, 0))
        self.lineEdit_3.setMaximumSize(QtCore.QSize(265, 16777215))
        self.lineEdit_3.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_7.addWidget(self.lineEdit_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_9 = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_4 = QtWidgets.QLineEdit(parent=self.widget_5)
        self.lineEdit_4.setMaximumSize(QtCore.QSize(265, 16777215))
        self.lineEdit_4.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_8.addWidget(self.lineEdit_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_28 = QtWidgets.QLabel(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_22.addWidget(self.label_28)
        self.comboBox = QtWidgets.QComboBox(parent=self.widget_5)
        self.comboBox.setStyleSheet("    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);")
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_22.addWidget(self.comboBox)
        self.verticalLayout_7.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.pushButton_13 = QtWidgets.QPushButton(parent=self.widget_5)
        self.pushButton_13.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_13.setFont(font)
        self.pushButton_13.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_13.setObjectName("pushButton_13")
        self.horizontalLayout_21.addWidget(self.pushButton_13)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.widget_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("\n"
"QPushButton{\n"
"height:30px;\n"
"border : none;\n"
"border-radius:10px;\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_21.addWidget(self.pushButton_2)
        self.pushButton_6 = QtWidgets.QPushButton(parent=self.widget_5)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(14)
        font.setBold(False)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"height:30px;\n"
"border : none;\n"
"border-radius:10px;\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_21.addWidget(self.pushButton_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        self.label_10 = QtWidgets.QLabel(parent=self.create_p)
        self.label_10.setGeometry(QtCore.QRect(480, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_10.setObjectName("label_10")
        self.stackedWidget.addWidget(self.create_p)
        self.update_p = QtWidgets.QWidget()
        self.update_p.setStyleSheet("")
        self.update_p.setObjectName("update_p")
        self.widget_6 = QtWidgets.QWidget(parent=self.update_p)
        self.widget_6.setGeometry(QtCore.QRect(130, 100, 861, 371))
        self.widget_6.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(170, 170, 255);\n"
"")
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_6)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_18 = QtWidgets.QLabel(parent=self.widget_6)
        self.label_18.setMinimumSize(QtCore.QSize(50, 50))
        self.label_18.setMaximumSize(QtCore.QSize(50, 50))
        self.label_18.setText("")
        self.label_18.setPixmap(QtGui.QPixmap(":/resources/user-avatarbb.png"))
        self.label_18.setScaledContents(True)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_9.addWidget(self.label_18)
        self.verticalLayout_8.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_15 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_16.addWidget(self.label_15)
        self.lineEdit_10 = QtWidgets.QLineEdit(parent=self.widget_6)
        self.lineEdit_10.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_16.addWidget(self.lineEdit_10)
        self.verticalLayout_8.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.lineEdit_5 = QtWidgets.QLineEdit(parent=self.widget_6)
        self.lineEdit_5.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_10.addWidget(self.lineEdit_5)
        self.verticalLayout_8.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_20 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_11.addWidget(self.label_20)
        self.lineEdit_6 = QtWidgets.QLineEdit(parent=self.widget_6)
        self.lineEdit_6.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_11.addWidget(self.lineEdit_6)
        self.verticalLayout_8.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_21 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_12.addWidget(self.label_21)
        self.lineEdit_7 = QtWidgets.QLineEdit(parent=self.widget_6)
        self.lineEdit_7.setMinimumSize(QtCore.QSize(60, 0))
        self.lineEdit_7.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.lineEdit_7.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_7.setText("")
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_12.addWidget(self.lineEdit_7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_22 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_13.addWidget(self.label_22)
        self.lineEdit_8 = QtWidgets.QLineEdit(parent=self.widget_6)
        self.lineEdit_8.setMaximumSize(QtCore.QSize(1000, 16777215))
        self.lineEdit_8.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_8.setText("")
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_13.addWidget(self.lineEdit_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_29 = QtWidgets.QLabel(parent=self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_29.setFont(font)
        self.label_29.setMouseTracking(False)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_23.addWidget(self.label_29)
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.widget_6)
        self.comboBox_2.setStyleSheet("    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.horizontalLayout_23.addWidget(self.comboBox_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.pushButton_14 = QtWidgets.QPushButton(parent=self.widget_6)
        self.pushButton_14.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_14.setFont(font)
        self.pushButton_14.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_14.setObjectName("pushButton_14")
        self.horizontalLayout_20.addWidget(self.pushButton_14)
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("\n"
"QPushButton{\n"
"height:30px;\n"
"border : none;\n"
"border-radius:10px;\n"
"background-color: rgb(85, 255, 255);\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_20.addWidget(self.pushButton_3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.label_23 = QtWidgets.QLabel(parent=self.update_p)
        self.label_23.setGeometry(QtCore.QRect(450, 50, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_23.setObjectName("label_23")
        self.stackedWidget.addWidget(self.update_p)
        self.delete_p = QtWidgets.QWidget()
        self.delete_p.setStyleSheet("")
        self.delete_p.setObjectName("delete_p")
        self.widget_7 = QtWidgets.QWidget(parent=self.delete_p)
        self.widget_7.setGeometry(QtCore.QRect(220, 140, 441, 241))
        self.widget_7.setStyleSheet("border-radius:10px;\n"
"background-color: rgb(170, 170, 255);\n"
"")
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_7)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_24 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_24.setMinimumSize(QtCore.QSize(50, 50))
        self.label_24.setMaximumSize(QtCore.QSize(50, 50))
        self.label_24.setText("")
        self.label_24.setPixmap(QtGui.QPixmap(":/resources/delete11.png"))
        self.label_24.setScaledContents(True)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_14.addWidget(self.label_24)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_25 = QtWidgets.QLabel(parent=self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.label_25.setFont(font)
        self.label_25.setLineWidth(0)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_15.addWidget(self.label_25)
        self.lineEdit_9 = QtWidgets.QLineEdit(parent=self.widget_7)
        self.lineEdit_9.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_9.setText("")
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_15.addWidget(self.lineEdit_9)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_16 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_16.setIndent(0)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_17.addWidget(self.label_16)
        self.lineEdit_11 = QtWidgets.QLineEdit(parent=self.widget_7)
        self.lineEdit_11.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_17.addWidget(self.lineEdit_11)
        self.verticalLayout_10.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_27 = QtWidgets.QLabel(parent=self.widget_7)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_18.addWidget(self.label_27)
        self.lineEdit_12 = QtWidgets.QLineEdit(parent=self.widget_7)
        self.lineEdit_12.setStyleSheet("\n"
"QLineEdit{\n"
"    border: 1px solid black;\n"
"    border-radius:5px;\n"
"    padding:5px;\n"
"    background: rgb(170, 255, 255);\n"
"}\n"
"QLineEdit::focus {\n"
"    border: 2px solid black;\n"
"}")
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_18.addWidget(self.lineEdit_12)
        self.verticalLayout_10.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.pushButton_15 = QtWidgets.QPushButton(parent=self.widget_7)
        self.pushButton_15.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton_15.setFont(font)
        self.pushButton_15.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.pushButton_15.setObjectName("pushButton_15")
        self.horizontalLayout_19.addWidget(self.pushButton_15)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("\n"
"QPushButton{\n"
"height:30px;\n"
"border : none;\n"
"border-radius:10px;\n"
"background-color: rgb(85, 255, 255);\n"
"}\n"
"")
        self.pushButton.setAutoRepeatDelay(296)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_19.addWidget(self.pushButton)
        self.verticalLayout_10.addLayout(self.horizontalLayout_19)
        self.label_26 = QtWidgets.QLabel(parent=self.delete_p)
        self.label_26.setGeometry(QtCore.QRect(300, 30, 281, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        self.label_26.setFont(font)
        self.label_26.setStyleSheet("color: rgb(0, 170, 255);")
        self.label_26.setScaledContents(False)
        self.label_26.setObjectName("label_26")
        self.stackedWidget.addWidget(self.delete_p)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.gridLayout.addWidget(self.widget_3, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        self.pushButton_11.toggled['bool'].connect(self.widget.setHidden) # type: ignore
        self.pushButton_11.toggled['bool'].connect(self.widget_2.setVisible) # type: ignore
        self.delete1.toggled['bool'].connect(self.pushButton_8.setChecked) # type: ignore
        self.update1.toggled['bool'].connect(self.update2.setChecked) # type: ignore
        self.create1.toggled['bool'].connect(self.create2.setChecked) # type: ignore
        self.dashboard1.toggled['bool'].connect(self.dashboard2.setChecked) # type: ignore
        self.dashboard2.toggled['bool'].connect(self.dashboard1.setChecked) # type: ignore
        self.create2.toggled['bool'].connect(self.create1.setChecked) # type: ignore
        self.update2.toggled['bool'].connect(self.update1.setChecked) # type: ignore
        self.pushButton_8.toggled['bool'].connect(self.delete1.setChecked) # type: ignore
        self.pushButton_9.toggled['bool'].connect(MainWindow.close) # type: ignore
        self.pushButton_10.toggled['bool'].connect(MainWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "Sidebar"))
        self.dashboard2.setText(_translate("MainWindow", "Dashboard"))
        self.create2.setText(_translate("MainWindow", "Create"))
        self.update2.setText(_translate("MainWindow", "Update"))
        self.pushButton_8.setText(_translate("MainWindow", "Delete"))
        self.pushButton_10.setText(_translate("MainWindow", "Log Out"))
        self.label_4.setText(_translate("MainWindow", "EMSI SMART"))
        self.label_12.setText(_translate("MainWindow", "WELCOME TO "))
        self.label_13.setText(_translate("MainWindow", "EMSI SMART"))
        self.label_17.setText(_translate("MainWindow", "Copyright © 2024 EMSI Smart. All rights reserved"))
        self.pushButton_4.setText(_translate("MainWindow", ""))
        self.pushButton_5.setText(_translate("MainWindow", " "))
        self.label_6.setText(_translate("MainWindow", "FirstName :"))
        self.label_7.setText(_translate("MainWindow", "LastName :"))
        self.label_8.setText(_translate("MainWindow", "Email :"))
        self.label_9.setText(_translate("MainWindow", "Password :"))
        self.label_28.setText(_translate("MainWindow", "Tache :"))
        self.pushButton_13.setText(_translate("MainWindow", "SAVE"))
        self.pushButton_2.setText(_translate("MainWindow", "Afficher"))
        self.pushButton_6.setText(_translate("MainWindow", ""))
        self.label_10.setText(_translate("MainWindow", "ADD EMPLOYER :"))
        self.label_15.setText(_translate("MainWindow", "ID :"))
        self.label_19.setText(_translate("MainWindow", "nom :"))
        self.label_20.setText(_translate("MainWindow", "Prenom :"))
        self.label_21.setText(_translate("MainWindow", "       Email :"))
        self.label_22.setText(_translate("MainWindow", "     Phone :"))
        self.label_29.setText(_translate("MainWindow", "       Tache :"))
        self.pushButton_14.setText(_translate("MainWindow", "EDIT"))
        self.pushButton_3.setText(_translate("MainWindow", "Afficher"))
        self.label_23.setText(_translate("MainWindow", "UPDATE EMPLOYER :"))
        self.label_25.setText(_translate("MainWindow", "ID"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Nom :</span></p></body></html>"))
        self.label_27.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:700;\">Prenom :</span></p></body></html>"))
        self.pushButton_15.setText(_translate("MainWindow", "DELETE"))
        self.pushButton.setText(_translate("MainWindow", "Afficher"))
        self.label_26.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:700;\">DELETE EMPLOYER :</span></p></body></html>"))
